# Generated by Django 2.0.9 on 2018-11-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_date',
            new_name='question_text',
        ),
    ]
